"""Reproducible portfolio demonstration; all customers and events are synthetic.
Run with Python 3.10+ from any working directory. No packages are required.
"""
from pathlib import Path
import random
import sqlite3

ROOT = Path(__file__).resolve().parent
rng = random.Random(42)
db = sqlite3.connect(":memory:")
db.executescript("""
CREATE TABLE customers (customer_id TEXT PRIMARY KEY);
CREATE TABLE months (month TEXT PRIMARY KEY);
CREATE TABLE purchases (
    purchase_id INTEGER PRIMARY KEY,
    customer_id TEXT NOT NULL REFERENCES customers(customer_id),
    month TEXT NOT NULL REFERENCES months(month),
    product TEXT NOT NULL,
    amount_cents INTEGER NOT NULL CHECK(amount_cents > 0),
    allowance_mb INTEGER NOT NULL CHECK(allowance_mb > 0),
    used_mb INTEGER NOT NULL CHECK(used_mb >= 0 AND used_mb <= allowance_mb)
);
""")
db.execute("PRAGMA foreign_keys = ON")
months = [f"2026-{month:02d}" for month in range(1, 7)]
db.executemany("INSERT INTO months VALUES (?)", [(m,) for m in months])
for customer in range(1, 201):
    customer_id = f"SYN{customer:04d}"
    db.execute("INSERT INTO customers VALUES (?)", (customer_id,))
    # Deliberately varied purchasing probabilities; these are design choices,
    # not an estimate of an operator's customer mix or product performance.
    probability = (0.9, 0.5, 0.15, 0.0)[(customer - 1) // 50]
    for month in months:
        if rng.random() >= probability:
            continue
        for _ in range(rng.randint(1, 4)):
            product = rng.choice(["EDG", "OTHER_DATA"])
            amount, allowance = (1000, 1024) if product == "EDG" else (2000, 2048)
            used = rng.randint(0, allowance)
            db.execute(
                "INSERT INTO purchases(customer_id,month,product,amount_cents,allowance_mb,used_mb) VALUES (?,?,?,?,?,?)",
                (customer_id, month, product, amount, allowance, used),
            )

# A fixed six-month eligible base is intentionally created before segmentation.
assert db.execute("SELECT COUNT(*) FROM customers").fetchone()[0] == 200
assert db.execute("SELECT COUNT(*) FROM months").fetchone()[0] == 6

db.executescript((ROOT / "sql/analysis.sql").read_text())
assert db.execute("SELECT COUNT(*) FROM customer_month").fetchone()[0] == 1200
assert db.execute("SELECT COUNT(*) FROM customer_segments").fetchone()[0] == 200
source_spend = db.execute("SELECT SUM(amount_cents) FROM purchases").fetchone()[0]
assert db.execute("SELECT SUM(spend_cents) FROM customer_segments").fetchone()[0] == source_spend
rows = db.execute("""
SELECT segment, COUNT(*) AS customers, SUM(purchase_count), SUM(spend_cents),
       ROUND(100.0 * SUM(spend_cents) / NULLIF((SELECT SUM(spend_cents) FROM customer_segments), 0), 2),
       ROUND(SUM(spend_cents) / 100.0 / COUNT(*) / 6, 2)
FROM customer_segments GROUP BY segment ORDER BY SUM(spend_cents) DESC
""").fetchall()
lines = ["# Synthetic prepaid purchasing results", "",
         "Generated by `python run_analysis.py`. Seed: 42. Window: January–June 2026.", "",
         "These results describe generated purchases, not actual telecom customers or company performance.", "",
         "| Segment | Customers | Purchases | Purchase value (R) | Share of value (%) | Value per eligible customer-month (R) |",
         "|---|---:|---:|---:|---:|---:|"]
for segment, customers, purchases, cents, share, monthly in rows:
    lines.append(f"| {segment} | {customers} | {purchases} | {cents/100:.2f} | {share:.2f} | {monthly:.2f} |")
lines += ["", "## Interpretation", "",
          "Differences between segments reflect the purchasing probabilities built into the synthetic generator. "
          "Purchase-month consistency is useful for describing this sample, but does not establish churn risk or future value.", "",
          "## Validation", "", "Passed: 200 unique eligible customers; 1,200 customer-month rows; "
          "one segment per customer; segment purchase value reconciles exactly to source transactions.", ""]
(ROOT / "RESULTS.md").write_text("\n".join(lines))
print("\n".join(lines))
